"$schema" = "https://starship.rs/config-schema.json"

format = "$directory$git_branch$git_status$character"
add_newline = false

[character]
# ğˆ³ á—‡ â¯
success_symbol = "[â¯](bold blue)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold blue)"
vimcmd_visual_symbol = "[â®](bold white)"

[git_branch]
style = "bold #aaaaaa"

[directory]
truncation_length = 2
truncate_to_repo = false
style = "bold #44adff"
read_only_style = "black"
